### ISSUE TITLE
升级组件库

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/fcc.chengdu#26]
- [x] Bootstrap v3 升 v5，推荐用 React Bootstrap 包装组件库：https://react-bootstrap.github.io/
- [x] Swiper 升级到官方 React 组件：https://swiperjs.com/react
- [x] Timeline 使用 React 生态中的平替组件：https://github.com/prabhuignoto/react-chrono

**Comment by luojiyin1987** [comment]
@TechQuery   我来做吧
